LICENSE
README.md

Please have a look at the README.md. I will provide more text in the next days.

Add a initial README.md & switch license to AGPLv3

---

app/controllers/incoming_controller.rb

commit 641e848 was also tested properly

IncomingController: log http body instead of params

---

app/models/pull_request.rb
db/migrate/20190730215048_add_author_to_pull_requests.rb

this adds a "please rebase" comment to the PR after adding the label.
This ensures the author gets notified

apply comment if PR needs a rebase

---

app/models/pull_request.rb
db/migrate/20190730215048_add_author_to_pull_requests.rb

Reverts voxpupuli/vox-pupuli-tasks#38

Revert "apply comment if PR needs a rebase"

---

app/models/pull_request.rb

Fixes https://github.com/voxpupuli/vox-pupuli-tasks/issues/42
Should be as simple as that

add requeue

---

app/views/dashboard/show.html.haml

Resolves https://github.com/voxpupuli/vox-pupuli-tasks/issues/31

unify repos in each type

---

.github/CODEOWNERS

This will always request a review from the group. It currently contains
Robert and Tim.

Configure codeowners

---

app/controllers/incoming_controller.rb
app/lib/github_event.rb

dont log known event types

---

config/initializers/voxpupuli.rb
config/voxpupuli.yml

move configuration to an actual config file

---

app/models/pull_request.rb

fix duplicate labels

---

app/lib/github_event/pull_request.rb
app/models/repository.rb

add check for all other pull requests in the repo on merge

---

app/models/pull_request.rb

add logging

---

app/models/pull_request.rb

enhance validation

---

app/models/pull_request.rb

enhance check

---

app/lib/github_event.rb

please the linter

---

app/models/pull_request.rb

log request and disabled comments

---

app/helpers/application_helper.rb
app/lib/travis_event.rb
app/models/pull_request.rb
app/models/repository.rb

improve logging

---

Gemfile
Gemfile.lock
config/initializers/lograge.rb

add lograge

---

.travis.yml
Dockerfile

use ruby 2.7

---

app/workers/repo_status_worker.rb

This fixes https://github.com/voxpupuli/vox-pupuli-tasks/issues/138

fix comparsion

---

app/controllers/application_controller.rb
app/views/dashboard/show.html.haml
app/views/layouts/application.html.haml

make login optional

---

db/migrate/20200429212046_add_uniq_index_to_repository.rb
db/schema.rb

This fixes https://github.com/voxpupuli/vox-pupuli-tasks/issues/137

add uniq index to repository name

---

app/models/pull_request.rb

This maybe fixes https://github.com/voxpupuli/vox-pupuli-tasks/issues/159

Only add a comment of PR is eligible

---

app/models/pull_request.rb
db/migrate/20200502221146_add_default_to_eligible_for_comment_in_pull_requests_modell.rb
db/schema.rb

In the past, we had no default value and mocked that in our modell. To
make this a bit more beautiful we now just set a default in the
database.

Cleanup eligible_for_comment attribute

---

app/controllers/dashboard_controller.rb
app/views/dashboard/show.html.haml

fix last status

---

app/models/pull_request.rb

fix update

---

app/models/pull_request.rb

fix validation

---

app/controllers/dashboard_controller.rb

filter nil checks

---

.gitignore

starting sidekiq via docker-compose will create this directory.

exclude sidekiq logs from git

---

.gitignore
README.md

Hello there,
I am opening a PR to add more specifics to the local setup steps in the README, as discussed last week (or the week before?) in IRC. I am also adding /log-sidekiq/ to the gitignore, as it gets created whenever the app comes up, following the local setup steps.
Let me know if I need to change anything :)
Thanks,
Blake Smreker

adding more specific steps for local setup / added sidekiq logs to gitignore

---

app/workers/validate_pull_request_worker.rb

add sentry logging

---

config/sidekiq.yml

disable retries

---

app/lib/github_event.rb

log github events

---

config/voxpupuli.yml

this also contains:
* https://github.com/voxpupuli/vox-pupuli-tasks/pull/261
* https://github.com/voxpupuli/vox-pupuli-tasks/pull/265
* https://github.com/voxpupuli/vox-pupuli-tasks/pull/266

Mark FreeBSD 13 as supported

---

config/voxpupuli.yml

this also contains https://github.com/voxpupuli/vox-pupuli-tasks/pull/261

mark CentOS 6 as EoL

---

config/voxpupuli.yml

this also contains:
* https://github.com/voxpupuli/vox-pupuli-tasks/pull/261
* https://github.com/voxpupuli/vox-pupuli-tasks/pull/265

mark Ubuntu 16.04 as EoL

---

.github/workflows/test-build-release.yml
.github/workflows/test-build.yml

ruby/setup-ruby has an option to manage the bundler dependencies and cache them.

Use bundler-cache in Github actions

---

Dockerfile

These two changes were required to build the vpt docker image on my local system.

Fix local docker build

---

Gemfile
Gemfile.lock
README.md
config/application.rb
docker-compose.yml

This has some changes for the local development instructions and adds basic otel tracing and jaeger for visualisation.

Integrate basic Jaeger for local dev

---

app/workers/refresh_pull_request_worker.rb

disclaimer: this is untested and fiddling around with `args` like this is probably wrong. copied it from https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/worker.rb#L169

RefreshPullRequestWorker: Check queue before performing jobs

---

Gemfile
Gemfile.lock
app/controllers/incoming_controller.rb
app/lib/github_event.rb
app/lib/travis_event.rb
app/models/pull_request.rb
app/models/repository.rb
app/workers/validate_pull_request_worker.rb

fix sentry

---

Gemfile
Gemfile.lock

fix sidekiq

---

app/lib/repository_checks/valid_sync_file.rb

fix typo in sync file check

---

app/lib/repository_checks/valid_sync_file.rb

See https://github.com/voxpupuli/puppet-posix_acl/blob/8ef409dde56b7079e14182d3342849cf9c3b7051/.sync.yml

fix error on empty yaml file

---

config/voxpupuli.yml

:wave: peeking in this repo, saw minor tweaks, though it would make sense to fix them.

Update the supported OS list

---

app/lib/repository_checks/missing_in_plumbing.rb
app/models/repo_status_data.rb
app/views/dashboard/show.html.haml
app/workers/repo_status_worker.rb
config/locales/en.yml

remove plumbing check

---

app/views/dashboard/_check_card.haml
app/views/dashboard/show.html.haml
config/locales/en.yml

A few more minor dashboard improvements.

Minor dashboard fixes

---

app/views/checks/show.html.haml
app/views/dashboard/show.html.haml

Filter the list so that only relevant modules are displayed: if the check was run, the check result is either true or false.  If the check was not run, it is nil.

Add links to operating system support check pages

---

Gemfile
Gemfile.lock

add net/smtp

---

Gemfile
Gemfile.lock

add net-pop and net-imap

---

app/workers/refresh_pull_request_worker.rb

Fix undefined local variable or method `id' for RefreshPullRequestWorker

---

config/voxpupuli.yml

We archived the repository.
ToDo: Implement a check to ignore archived repos?

puppet-face: mark it as archived

---

app/models/pull_request.rb

Fix call for last check_suite
