- app/assets/stylesheets/application.scss
A couple of things:
We deploy the site with HTTPS, so loading assets with HTTP doesn't work
in general. Also loading external content is a bad idea, it exposes
users data. Also the host is dead and returns NXDOMAIN.
> drop dead fonts URL

- README.md
- app/models/label.rb
- app/models/pull_request.rb
`needs-rebase` might be added when something got merged to master that's
missing in a feature branch. `merge-conflicts` are actual git conflicts.
Those are detectable by this application. The color stays the same, as
bove labels are for the same topic.
> use `merge-conflicts` instead of `needs-rebase`

- app/controllers/incoming_controller.rb
Do not log if a valid request is registred and stop processing if an invalid one is seen.
> improve webhook security

- app/workers/repo_status_worker.rb
this should fix:
```
NoMethodError: undefined method `supports_eol_centos' for #<Hash:0x0000560a8c259990>
```
this explicit return statement was already present...
> RepoStatusWorker: explicitly return `data` in check_metadatas

- README.md
- config/locales/en.yml
- config/voxpupuli.yml
Puppet Inc. started to deprecate modules with Ubuntu 14.04 so we should
drop it as well. For example: https://forge.puppet.com/puppetlabs/inifile/changelog#v400-2019-11-11
> Drop Ubuntu 14.04

- .travis.yml
We switched the baseimage from 16.04 to 18.04. It now bundles 2.6.3 by
default. Other ruby versions need to be installed, which takes time.
Switching to 2.6.3 will speed up our travis runs.
> travis: switch Ruby 2.5.3->2.6.3

- app/models/pull_request.rb
The `ensure_label_is_attached` method returns a hash if the label has been attached and nil if it did not attach a label.
So we only add a comment if the label has been attached.
I left the comment flag intact. It is not really needed anymore - but if we do not remove it we do not break anything in our validation logic now.
> try to fix duplicate comments

- app/controllers/incoming_controller.rb
- app/lib/travis_event.rb
- app/lib/travis_event/base.rb
- app/lib/travis_event/push.rb
- app/models/travis.rb
- config/routes.rb
Fixes https://github.com/voxpupuli/vox-pupuli-tasks/issues/61
(in parts)
> implement travis event handling

- app/models/repository.rb
- app/workers/index_repos_worker.rb
- app/workers/sync_label_worker.rb
- db/migrate/20200426200729_add_description_to_labels.rb
- db/schema.rb
Create methods to find missing Labels on our Repositories
Add a worker which is triggered with every IndexReposWorker run
to ensure we have all the Labels from our config in our Repositories
on GitHub
This tackles https://github.com/voxpupuli/vox-pupuli-tasks/issues/131
> handle labels

- Gemfile
- Gemfile.lock
Arch, for reasons that no-one can explain, does not ship irb in their
ruby package. Everything else relies on it. To use it properly, we need
to install it via Gemfile.
> Add `irb` to development gems

- app/models/pull_request.rb
- app/workers/update_mergeable.rb
If a PR comes in and has no `mergeable` attribute, we put a job into our
queue for a minute. Afterwards we checked the PR status twice. This
isn't required. This patch removed the duplicate check.
> Dont validate a queued PR twice

- app/models/label.rb
- app/models/pull_request.rb
- config/locales/en.yml
> Set a PR label / comment if CI passes/fails

- app/models/pull_request.rb
- db/migrate/20200501212046_add_status_to_pull_requests.rb
- db/schema.rb
This will be a series of PRs:
* Save combined CI status as pull_request attribute
* Use that to validate if we should a comment/label about CI failures
* Not only set label/comment if CI is broken, but if the state changes (use saved_changes)
> Save CI status as PR attribute

- app/models/pull_request.rb
- db/migrate/20200502213446_add_draft_to_pull_requests.rb
- db/schema.rb
We should not label/comment on a draft PR. To detect this, we should
save the state.
> pull_request: save draft state

- app/models/pull_request.rb
- db/migrate/20200502221147_fix_column_name.rb
- db/migrate/20200502221148_add_eligible_for_ci_comment.rb
- db/schema.rb
Depends on https://github.com/voxpupuli/vox-pupuli-tasks/pull/165 / should be rebased after that's merged.
> Rename eligible_for_{,merge}comment / Prevent duplicate CI comments

- config/database.yml
- docker-compose.yml
The idea is that development/test run locally without docker, but
connect to the postgres instance provided via docker-compose. Our
production setup runs in a container and connects via docker network to
postgres.
> Cleanup dev/prod database setup

- .dockerignore
- .gitignore
In case people use the docker-compose file in this directory without
moving it, docker creates a postgres-data subdir. That won't be
accessible from the local user and therefore breaks git commands but
also docker build.
> Ignore postres-data directory

- Gemfile
- Gemfile.lock
caused by https://github.com/fomantic/Fomantic-UI-SASS/issues/8
> pin fomantic-ui-sass to 2.8.4

- app/models/pull_request.rb
- app/workers/validate_pull_request_worker.rb
> :hammer: Please the linter

- db/migrate/20200723172636_add_uniq_index_to_pull_request.rb
- db/migrate/20200723173538_add_uniq_index_to_repository2.rb
- db/schema.rb
tested this locally:
```
$ bundle exec rake db:migrate
I, [2020-07-23T19:40:16.210780 #55735]  INFO -- sentry: ** [Raven] Raven 2.13.0 configured not to capture errors: DSN not set
DEPRECATION WARNING: Single arity template handlers are deprecated. Template handlers must
now accept two parameters, the view object and the source for the view object.
Change:
>> Coffee::Rails::TemplateHandler.call(template)
To:
>> Coffee::Rails::TemplateHandler.call(template, source)
(called from <top (required)> at /home/bastelfreak/vox-pupuli-tasks/Rakefile:8)
== 20200723172636 AddUniqIndexToPullRequest: migrating ========================
-- add_index(:pull_requests, :github_id, {:unique=>true})
-> 0.0229s
== 20200723172636 AddUniqIndexToPullRequest: migrated (0.0230s) ===============
== 20200723173538 …
```
> Add Uniq constraint to github_id

- .rubocop_todo.yml
- app/models/pull_request.rb
the status is pending if one configured check is still running. If a PR
was just created, the checks haven't passed/failed yet. This wouldn't be
bad IF we would get notifications if they finish. This superseeds
https://github.com/voxpupuli/vox-pupuli-tasks/pull/214
> (#213) queue PR update if status is `pending`

- .github/workflows/ruby.yml
tl;dr v1 is broken and poorly documented. We raised those concerns via
an issue. That should be fixed in v2: https://github.com/docker/build-push-action/issues/88#event-3748118416
> Fix docker releases via GitHub actions

- .github/workflows/test-build-release.yml
- .github/workflows/test-build.yml
With this PR we rework our GitHub actions and split them into two. One
is triggered for pull requests and executes our tests. The second one
runs for merges onto master. It executes the test as well but also
builds the docker image and pushes it to DockerHub.
> Rework GitHub Actions / release only on merges

- config/sidekiq.yml
To avoid multiple concurrent jobs that might conflict, we set the
concurrency to 1.
Stolen from
https://github.com/mperham/sidekiq/wiki/Advanced-Options#the-sidekiq-configuration-file
/ https://github.com/voxpupuli/puppet_webhook/pull/156
> Sidekiq: Set concurrency to 1

- .rubocop_todo.yml
- app/models/pull_request.rb
This is a rebase of https://github.com/voxpupuli/vox-pupuli-tasks/pull/214
The original commit message:
---
the status is pending if one configured check is still running. If a PR
was just created, the checks haven't passed/failed yet. This wouldn't be
bad IF we would get notifications if they finish. We could implement
travis CI notification parsing for this, but people might implement
other checks as well. We can simply queue a job that updates the PR.
This fixes https://github.com/voxpupuli/vox-pupuli-tasks/issues/213 in parts. If we update the PR and the status is still
pending, we don't queue another job. After some thoughts it's probably a
good idea to move the logic from validate_status() to
`queue_validation()` and `validate()`.
> Queue a PR refresh if CI status is pending

- app/workers/validate_pull_request_worker.rb
In the past we compared arrays by sorting & comparing them:
```
array1.sort == array2.sort
```
rubys array comparsion is order dependent:
```
irb(main):015:0> [1, 2] == [2, 1]
=> false
```
that's why we usually sort them first. But we cannot sort heterogenous
arrays:
```
irb(main):032:0> ["puppet-firewalld", 299].sort
Traceback (most recent call last):
2: from (irb):32
1: from (irb):32:in `sort'
ArgumentError (comparison of String with 299 failed)
irb(main):033:0>
```
`tally()` got introduced in Ruby 2.7 and counts the occurences of all
elements:
```
irb(main):029:0> ['1', 2].tally
=> {"1"=>1, 2=>1}
```
This means we can call `tally()` on both arrays, convert the return
value to an array and create a new set and check if that's empty:
```
irb(main):030:0> ['1', 2].tally.to_a - [2, …
```
> Compare heterogenous arrays via tally()

- .github/workflows/test-build.yml
- Gemfile.lock
The used version 0.3.5 got pulled from rubygems so we cannot install the
application anymore. Instead of updating all gems, which would require
more testing, we only update mimemagic for now.
This PR also contains https://github.com/voxpupuli/vox-pupuli-tasks/pull/262
> mimemagic: Update 0.3.5->0.3.10 

- .github/workflows/test-build.yml
THe old pinned version doesn't work anymore due to changes in the action
and the environment. It used set-env which is now deprecated: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> GitHub Actions: Use latest ruby/setup-ruby@v1 action

- config/voxpupuli.yml
Puppet 5 is now end of life and Puppet 7 got released some time ago.
> Update supported puppet versions to `>=6.1.0 < 8.0.0`

- Gemfile
- Gemfile.lock
We don't need it since we migrated to github actions.
> Gemfile: drop legacy travis gem

- Gemfile.lock
- app/controllers/incoming_controller.rb
- app/lib/github_event.rb
- app/lib/travis_event.rb
- app/models/pull_request.rb
- app/models/repository.rb
- app/workers/validate_pull_request_worker.rb
> use sentry not raven

- app/views/dashboard/show.html.haml
All modules do not support all operating systems.
The #check_operating_system_support method iterates on each supported
operating system and set `supports_only_current_<os>` and
`supports_latest_<os>` accordingly.  We can therefore check if a value
was registered or not for them, i.e. true and false vs. nil.
Each OS will then display the number of up-to-date modules compared to
the number of modules which idealy should be up-to-date, and not
compared to all existing modules.
> Improve Operating System support stats

- .github/workflows/test-build-release.yml
- .github/workflows/test-build.yml
We really don't use this information at the moment.
> Dont output image digest
